name: Windows Build
on:
    workflow_dispatch:

jobs:
    build:
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: Install VS Dependencies
              run:
                choco install visualstudio2022-workload-nativedesktop --package-parameters "--includeRecommended --includeOptional"

            - name: Install MSYS
              uses: msys2/setup-msys2@v2
              with:
                msystem: MINGW64
                
            - name: Install Doxygen
              uses: ssciwr/doxygen-install@v1

            - name: Install YASM
              run: |
                mkdir ${{ github.workspace }}\utils\yasm
                cd ${{ github.workspace }}\utils\yasm
                curl http://www.tortall.net/projects/yasm/releases/yasm-1.3.0-win64.exe -o yasm.exe
                "${{ github.workspace }}\utils\yasm;" | Out-File -FilePath $env:GITHUB_PATH -Append

            - name: Echo Path
              shell: cmd
              run: |
                echo %PATH%

            - name: Build Libvpx
              shell: msys2 {0}
              run: |
                cd ${{github.workspace}}
                configure "--enable-multithread" "--enable-realtime-only" "--enable-spatial-resampling" "--enable-vp8" "--disable-vp9" "--enable-libs" "--disable-install-docs" "--disable-debug-libs" "--disable-examples" "--disable-tools" "--as=yasm" "--prefix=${{github.workspace}}/output" "--target=x86_win64-vs17"
                cd build/make
                bash -l -c make
                bash -l -c install

            - name: Upload log
              uses: actions/upload-artifact@v4
              if: always()
              with:
                name: Config log
                path: ${{ github.workspace }}
                overwrite: true